version: '3.8'

services:
  ipfs:
    image: ipfs/kubo:latest
    container_name: ipfs-node
    restart: unless-stopped
    ports:
      - "4001:4001"   # Puerto para la red IPFS (para conexiones entre nodos)
      - "5001:5001"   # API de IPFS (para interactuar con el nodo)
      - "8080:8080"   # Gateway HTTP de IPFS (para acceder a archivos desde el navegador)
    volumes:
      - ipfs_data:/data/ipfs
    environment:
      - IPFS_PROFILE=server  # Modo optimizado para servidores
      - IPFS_LOGGING=info    # Nivel de logs (info, debug, error)
    command: ["daemon", "--migrate=true"]

volumes:
  ipfs_data:
    driver: local
